[trifinger_rl_experiment]
task = "lift"  # "push" or "lift"

# Specify a policy for each task.
push_policy = "trifinger_decision_transformer.decision_transformer.DTPushPolicy"
lift_policy = "trifinger_decision_transformer.decision_transformer.DTLiftPolicy"
